name: Android Build

on:
  push:
    branches:
      - main
      - qa
      - "release/**"
    tags:
      - "v*"
  pull_request:
    branches:
      - main
      - qa
      - "release/**"
  workflow_dispatch:

jobs:
  build:
    name: Build Camerae Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build
        working-directory: android
        run: ./gradlew assembleDebug
